import { UserType } from '../../types';

export const user: UserType = {
  id: 'LSQFf587g90',
  tier: 1,
  balance: 200000,
  accountNumber: 9912345678,
  bankName: 'Providus Bank',
  fullName: 'Grace Effiom',
  email: 'grace@gmail.com',
  phoneNumber: '07060780922',
  BVN: '07060780922',
  maritalStatus: 'Single',
  gender: 'Female',
  children: 'None',
  typeOfResidence: "Parent's Apartment",
  levelOfEducation: 'B.Sc',
  employmentStatus: 'Employed',
  sectorOfEmployment: 'FinTech',
  durationOfEmployment: '2 years',
  officeEmail: 'grace@lendsqr.com',
  monthlyIncomeMin: 200000,
  monthlyIncomeMax: 400000,
  loanRepayment: 40000,
  twitterHandle: '@grace_effiom',
  facebookHandle: 'Grace Effiom',
  intagramHandle: '@grace_effiom',
  guarantorFullName: 'Debby Ogana',
  guarantorEmail: 'debby@gmail.com',
  guarantorPhoneNumber: '07060780922',
  guarantorRelationship: 'Sister',
  username: 'Grace',
  status: 'Active',
  organization: 'Lendsqr',
  dateJoined: 'May 5, 2018 10:00 AM',
};
