import { UserType } from '../../types';

export const tableHeaders = [
  {
    id: 1,
    name: 'ORGANIZATION',
  },
  {
    id: 2,
    name: 'USERNAME',
  },
  {
    id: 3,
    name: 'EMAIL',
  },
  {
    id: 4,
    name: 'PHONE NUMBER',
  },
  {
    id: 5,
    name: 'DATE JOINED',
  },
  {
    id: 6,
    name: 'STATUS',
  },
];

export const tableBodyContents: Array<UserType> = [
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
  {
    id: 'KKBQf931c85',
    tier: 2,
    balance: 350000,
    accountNumber: 3212377674,
    bankName: 'Providus Bank',
    fullName: 'Samuel Adedeji',
    email: 'sam@gmail.com',
    phoneNumber: '07037780911',
    BVN: '07037780911',
    maritalStatus: 'Single',
    gender: 'Male',
    children: 'None',
    typeOfResidence: 'Apartment',
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '3 years',
    officeEmail: 'sam@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@sam_adedeji',
    facebookHandle: 'Samuel Adedeji',
    intagramHandle: '@sam_adedeji',
    guarantorFullName: 'Mark Adedeji',
    guarantorEmail: 'mark@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Brother',
    username: 'Adedeji',
    status: 'Inactive',
    organization: 'Lendsqr',
    dateJoined: 'May 15, 2020 10:00 AM',
  },
  {
    id: 'LSQFf587g90',
    tier: 1,
    balance: 200000,
    accountNumber: 9912345678,
    bankName: 'Providus Bank',
    fullName: 'Grace Effiom',
    email: 'grace@gmail.com',
    phoneNumber: '07060780922',
    BVN: '07060780922',
    maritalStatus: 'Single',
    gender: 'Female',
    children: 'None',
    typeOfResidence: "Parent's Apartment",
    levelOfEducation: 'B.Sc',
    employmentStatus: 'Employed',
    sectorOfEmployment: 'FinTech',
    durationOfEmployment: '2 years',
    officeEmail: 'grace@lendsqr.com',
    monthlyIncomeMin: 200000,
    monthlyIncomeMax: 400000,
    loanRepayment: 40000,
    twitterHandle: '@grace_effiom',
    facebookHandle: 'Grace Effiom',
    intagramHandle: '@grace_effiom',
    guarantorFullName: 'Debby Ogana',
    guarantorEmail: 'debby@gmail.com',
    guarantorPhoneNumber: '07060780922',
    guarantorRelationship: 'Sister',
    username: 'Grace',
    status: 'Active',
    organization: 'Lendsqr',
    dateJoined: 'May 5, 2018 10:00 AM',
  },
];

export const statusColumnClassname = (status: string) =>
  status === 'Blacklisted'
    ? 'blacklisted'
    : status === 'Inactive'
    ? 'inactive'
    : status === 'Pending'
    ? 'pending'
    : status === 'Active'
    ? 'active'
    : '';
